flags: {}
extra-package-dbs: []
packages:
- './safepath'
- './safepath-testing'
- location: /home/syd/validity/validity
  extra-dep: true
- location: /home/syd/validity/validity-containers
  extra-dep: true
- location: /home/syd/validity/genvalidity
  extra-dep: true
- location: /home/syd/validity/genvalidity-containers
  extra-dep: true
- location: /home/syd/validity/genvalidity-text
  extra-dep: true
- location: /home/syd/validity/genvalidity-hspec
  extra-dep: true
compiler: ghc-8.0.1
resolver: nightly-2016-06-05
